spring:
  datasource:
    url: jdbc:mysql://localhost:3308/itcast
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

scheduler:
  news:
    crawling: "0 0 */3 * * ?"
    old-delete-data: "0 0 0 1 1,7 ?"
    select-news: "0 0 6 * * ?"
    send-alarm: "0 0 8 * * ?"
  blog:
    crawling: "0 0 */3 * * ?"
    selecting: "0 0 6 * * *"
    sending: "0 0 8 * * *"
    # "30/30 * * * * *"
  timeout:
    connection: 5000

openai:
  blog-prompt: |
    \n\n
    내용을 보고 요약해주세요. 그리고 GPT가 생각하기에 프론트엔드 쪽인지 백엔드 쪽인지 판별해주고 읽었을때 점수를 매겨줄 수 있을까요?
    **필수 조건**:
        1. 응답 형식을 필수적으로 맞춰서 작성해야합니다.
        2. 카테고리를 정할 때 무조건 NEWS로 주어야 합니다.
        3. 점수는 점수 조건에 따라 0에서 10까지의 정수로 알려주시고 GPT가 생각하기에 내용에 대한 유익한 점수를 매겨줄 수 있나요?
        4. 답변은 존댓말로 해주세요.
    **점수 조건**:
    1. 유익성 (4점)
        3점: 정보가 매우 유익하고, 독자가 바로 실용적인 지식이나 기술을 얻을 수 있다. 특히 실무에서 즉시 적용할 수 있는 구체적인 해결책을 제공한다.
        2점: 정보가 유익하지만 다소 추상적이거나 추가적인 예시나 설명이 부족하여 독자가 적용하기 전에 추가적인 노력이 필요하다.
        1점: 제공되는 정보가 유익하긴 하지만 명확하지 않거나 구체적인 적용 방법을 제시하지 않는다.
        0점: 정보가 유익하지 않거나, 실용적인 가치를 제공하지 않는다.
    2. 작성의 명료성 (3점)
        3점: 문장이 명확하고 일관되며, 논리적인 흐름이 자연스럽다. 독자가 쉽게 이해할 수 있도록 중요한 부분이 잘 강조되며 복잡한 개념을 간결하게 설명한다.
        2점: 대부분 명확하지만 다소 복잡하거나 어려운 문장이 있어 부분적으로 독자가 이해하는 데 시간이 걸린다.
        1점: 문장이 혼란스럽거나 지나치게 복잡하여 독자가 이해하는 데 어려움이 많다.
        0점: 내용이 지나치게 혼란스럽거나 구조적으로 어색해 독자가 이해하기 힘들다.
    3. 독창성 및 참신함 (3점)
        3점: 기존의 개념이나 주제를 매우 창의적이고 새로운 방식으로 접근하거나 독자에게 새로운 시각을 제공한다. 기존 정보에서 한 걸음 더 나아간 분석이나 예시가 포함된다.
        2점: 주제나 개념이 다소 일반적이지만, 일정 부분에서 새로운 관점이나 해석을 제공한다.
        1점: 내용이 기존의 정보나 접근 방식에 큰 차별점 없이 반복적이다.
        0점: 기존 정보와 전혀 다른 관점을 제시하지 않거나 반복적이고 창의성이 부족하다.
    4. 종합 점수 (10점 만점)
        각 항목의 점수를 합산하여 최종 점수를 매긴다.
    **응답 형식**:
    {
      "category" : [FRONTEND or BACKEND]
      "summary" : [요약 내용]
      "rating" : [점수]
    }
  news-prompt: |
    \n\n
    내용을 보고 요약해주세요. 그리고 GPT가 읽었을때 점수를 매겨줄 수 있을까요? 
    **필수 조건**:
        1. 응답 형식을 필수적으로 맞춰서 작성해야합니다.
        2. 카테고리를 정할 때 무조건 NEWS로 주어야 합니다.
        3. 점수는 점수 조건에 따라 0에서 10까지의 정수로 알려주시고 GPT가 생각하기에 내용에 대한 유익한 점수를 매겨줄 수 있나요?
        4. 답변은 존댓말로 해주세요.
    **점수 조건**:
    1. 유익성 (4점)
        3점: 정보가 매우 유익하고, 독자가 바로 실용적인 지식이나 기술을 얻을 수 있다. 특히 실무에서 즉시 적용할 수 있는 구체적인 해결책을 제공한다.
        2점: 정보가 유익하지만 다소 추상적이거나 추가적인 예시나 설명이 부족하여 독자가 적용하기 전에 추가적인 노력이 필요하다.
        1점: 제공되는 정보가 유익하긴 하지만 명확하지 않거나 구체적인 적용 방법을 제시하지 않는다.
        0점: 정보가 유익하지 않거나, 실용적인 가치를 제공하지 않는다.
    2. 작성의 명료성 (3점)
        3점: 문장이 명확하고 일관되며, 논리적인 흐름이 자연스럽다. 독자가 쉽게 이해할 수 있도록 중요한 부분이 잘 강조되며 복잡한 개념을 간결하게 설명한다.
        2점: 대부분 명확하지만 다소 복잡하거나 어려운 문장이 있어 부분적으로 독자가 이해하는 데 시간이 걸린다.
        1점: 문장이 혼란스럽거나 지나치게 복잡하여 독자가 이해하는 데 어려움이 많다.
        0점: 내용이 지나치게 혼란스럽거나 구조적으로 어색해 독자가 이해하기 힘들다.
    3. 독창성 및 참신함 (3점)
        3점: 기존의 개념이나 주제를 매우 창의적이고 새로운 방식으로 접근하거나 독자에게 새로운 시각을 제공한다. 기존 정보에서 한 걸음 더 나아간 분석이나 예시가 포함된다.
        2점: 주제나 개념이 다소 일반적이지만, 일정 부분에서 새로운 관점이나 해석을 제공한다.
        1점: 내용이 기존의 정보나 접근 방식에 큰 차별점 없이 반복적이다.
        0점: 기존 정보와 전혀 다른 관점을 제시하지 않거나 반복적이고 창의성이 부족하다.
    4. 종합 점수 (10점 만점)
        각 항목의 점수를 합산하여 최종 점수를 매긴다.
    **응답 형식**:
    {
      "category" : NEWS
      "summary" : [요약 내용]
      "rating" : [점수]
    }

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

server:
  port: 8081
